# ============================================================================
# Example GitHub Actions workflow for Playwright + Smart Reporter
#
# Copy this file to .github/workflows/playwright.yml in your project.
# Adjust paths and options to match your setup.
# ============================================================================

name: Playwright Tests with Smart Reporter

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Install project dependencies
      - run: npm ci

      # 4. Install Playwright browsers and OS dependencies
      - run: npx playwright install --with-deps

      # 5. Run Playwright tests
      #    Smart Reporter generates the HTML report automatically based
      #    on your playwright.config.ts reporter configuration.
      #
      #    Optional env vars:
      #    - OPENAI_API_KEY / ANTHROPIC_API_KEY / GEMINI_API_KEY: enables AI failure analysis
      #    - SMART_REPORTER_LICENSE_KEY: unlocks Pro features (PDF export, notifications, etc.)
      - run: npx playwright test
        env:
          # AI-powered failure analysis (set these in GitHub repo Settings > Secrets)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          # GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          # Pro license (optional - enables PDF export, notifications, quality gates)
          # SMART_REPORTER_LICENSE_KEY: ${{ secrets.SMART_REPORTER_LICENSE_KEY }}

      # 6. Upload the Smart Reporter HTML report as a build artifact
      #    The report is available in the Actions tab under "Artifacts"
      - uses: actions/upload-artifact@v4
        if: always()  # Upload even when tests fail
        with:
          name: smart-report
          path: smart-report.html
          retention-days: 30

      # 7. (Optional) Upload test results directory for traces/screenshots
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 7

  # ============================================================================
  # Optional: Sharded test execution for large test suites
  # ============================================================================
  # sharded-test:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 15
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       shard: [1/4, 2/4, 3/4, 4/4]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #     - run: npm ci
  #     - run: npx playwright install --with-deps
  #     - run: npx playwright test --shard=${{ matrix.shard }}
  #       env:
  #         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #     - uses: actions/upload-artifact@v4
  #       if: always()
  #       with:
  #         name: smart-report-shard-${{ strategy.job-index }}
  #         path: smart-report.html
  #         retention-days: 30

  # ============================================================================
  # Optional: Slack notification on failure (requires Pro license)
  # ============================================================================
  # notify:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: failure()
  #   steps:
  #     - name: Notify team
  #       run: |
  #         echo "Tests failed - Smart Reporter notifications handle this automatically"
  #         echo "Configure 'notifications' in playwright.config.ts for Slack/Teams/PagerDuty"
